server:
  context-path: /api
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lkk_piano?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 10
    minIdle: 100
    maxActive: 3000
    maxWait: 3000
    testOnBorrow: true
    filter: stat,wall
    validationQuery: SELECT 1 FROM DUAL

#logging:
#  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bean
  configuration:
      mapUnderscoreToCamelCase: true